from zoneinfo import ZoneInfo

SERVER_TZ = ZoneInfo("Europe/Warsaw")

COOLDOWN_MINUTES = 30
GLOBAL_ATTACK_COOLDOWN_SEC = 30
DAILY_ATTACK_LIMIT = 20
PRESTIGE_GAIN_CAP = 300
PRESTIGE_LOSS_CAP = 250

BASE_GAIN = 30
BASE_LOSS = 25
EXPECTED_WIN_BASE = 0.35
EXPECTED_WIN_DIVISOR = 2000
EXPECTED_WIN_MIN = 0.15
EXPECTED_WIN_MAX = 0.85

DECAY_THRESHOLD = 1200
DAILY_DECAY_RATE = 0.06
DAILY_DECAY_MAX = 60
INACTIVITY_GRACE = 2
INACTIVITY_MULT = 1.5
